Repository PI-Akatsuki/PIOMS.FE, pull requests merged in 2024-05, with the labels that each got.

#1 CI/CD and settings
  .github/ISSUE_TEMPLATE/pioms_be-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  jest.unit.config.cjs
  package-lock.json
  package.json
  src/router/router.js
Labels: ⚙ Setting

#2 Create FrontCode of Ask by Admin and environment
  package-lock.json
  package.json
  src/App.vue
  src/assets/icon/List.png
  src/assets/icon/reset.png
  src/assets/icon/search.png
  src/components/franchise/ask/AskMain.vue
  src/components/franchise/ask/Breadcrumb.vue
  src/components/franchise/아래에폴더단위.vue
  src/main.js
  src/router/router.js
Labels: ✨ Feature, 🔨 Refactor

#3 Implementation of Order page
  package-lock.json
  src/components/order/orderDetail.vue
  src/components/order/orderPopup.vue
  src/components/order/orderProductList.vue
  src/components/order/pagination.vue
  src/main.js
Labels: 🎨 Html&css, ✨ Feature

#5 Create askAnswerRegisterForm,askAnswerEditForm and change environment
  package-lock.json
  package.json
  src/App.vue
  src/assets/css/main.css
  src/components/franchise/ask/AnswerFormEdit.vue
  src/components/franchise/ask/AnswerFormRegister.vue
  src/components/franchise/ask/AskMain.vue
  src/router/router.js
Labels: ✨ Feature, 🔨 Refactor

#6 Update ISSUE Template
  .github/ISSUE_TEMPLATE/pioms_be-issue-template.md
  package-lock.json
  package.json
  src/App.vue
  src/assets/css/main.css
  src/assets/icon/List.png
  src/assets/icon/reset.png
  src/assets/icon/search.png
  src/components/franchise/ask/AnswerFormEdit.vue
  src/components/franchise/ask/AnswerFormRegister.vue
  src/components/franchise/ask/AskMain.vue
  src/components/franchise/ask/Breadcrumb.vue
  src/components/franchise/아래에폴더단위.vue
  src/components/order/orderDetail.vue
  src/components/order/orderPopup.vue
  src/components/order/orderProductList.vue
  src/components/order/pagination.vue
  src/main.js
  src/router/router.js
Labels: 📃 Docs

#8 Ask code refactor
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/amdin/ask/AskMain.vue
  src/components/amdin/ask/Breadcrumb.vue
  src/router/router.js
Labels: ✨ Feature, 🔨 Refactor

#9 Administrator login API integration
  package-lock.json
  package.json
  src/assets/icon/PIOMS_로고.png
  src/components/login/AdminLogin.vue
  src/components/login/CommonLogin.vue
  src/components/login/DriverLogin.vue
  src/components/login/FranchiseLogin.vue
  src/components/login/Login.vue
  src/router/router.js
  src/store/store.js
Labels: 🎨 Html&css, 📬 API

#11 View all product by admin
  package-lock.json
  package.json
  src/App.vue
  src/components/amdin/Category/CategoryList.vue
  src/components/amdin/product/ProductList.vue
  src/components/order/orderPopup.vue
  src/router/router.js
Labels: 🎨 Html&css, 🔨 Refactor

#20 View ProductList and Create product(popup) with imageCloud
  src/App.vue
  src/assets/icon/picture.png
  src/components/amdin/product/ProductDetailPopup.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
  src/router/router.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor, 📬 API

#24 Update product and product list excel download by Admin
  .github/ISSUE_TEMPLATE/pioms_be-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .vscode/extensions.json
  src/assets/icon/excel.png
  src/components/amdin/product/ProductDetailPopup.vue
  src/components/amdin/product/ProductList.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#27 Add File & Create Header, Footer, Sidebar File / Header, Footer for Root Admin
  package-lock.json
  src/App.vue
  src/assets/icon/PIOMS매미.png
  src/assets/icon/public/Calendar.png
  src/assets/icon/public/Cloth.png
  src/assets/icon/public/Delivery.png
  src/assets/icon/public/Document.png
  src/assets/icon/public/Exchange.png
  src/assets/icon/public/Graph.png
  src/assets/icon/public/GraySearch.png
  src/assets/icon/public/Group.png
  src/assets/icon/public/Homepng.png
  src/assets/icon/public/List.png
  src/assets/icon/public/Log.png
  src/assets/icon/public/Notice.png
  src/assets/icon/public/PIOMSDelivery.png
  src/assets/icon/public/Reason.png
  src/assets/icon/public/Smilepng.png
  src/assets/icon/public/Store.png
  src/assets/icon/public/View.png
  src/assets/icon/public/excel.png
  src/assets/icon/public/invoicePrint.png
  src/assets/icon/public/reset.png
  src/assets/icon/public/search.png
  src/assets/icon/public/upload.png
  src/components/config/footer/Footer.vue
  src/components/config/header/AdminHeader.vue
  src/components/config/header/DriverHeader.vue
  src/components/config/header/FranchiseHeader.vue
  src/components/config/header/RootAdmin.vue
  src/components/config/sidebar/sidebar.vue
  src/components/notice/noticeList.vue
Labels: 🎨 Html&css, ✨ Feature, 📃 Docs

#28 feat: add post product with image
  src/App.vue
  src/assets/css/order.css
  src/components/amdin/product/ProductPostPopup.vue
  src/components/order/orderDetail.vue
  src/components/order/orderPage.vue
  src/components/order/orderProductList.vue
  src/router/router.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#45 Full implementation of the login page
  package-lock.json
  package.json
  src/App.vue
  src/assets/css/base.css
  src/assets/css/main.css
  src/components/login/AdminLogin.vue
  src/components/login/CommonLogin.vue
  src/components/login/DriverLogin.vue
  src/components/login/FranchiseLogin.vue
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#46 Refactoring FE favorite register & view
  src/assets/icon/Dictionary.png
  src/assets/icon/dashboard.png
  src/assets/icon/root/Crown.png
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/favorite/FavoriteRegister.vue
  src/router/router.js
Labels: 🎨 Html&css, 🔨 Refactor

#50 View Categories and Update Category First by Root
  src/App.vue
  src/components/amdin/Category/CategoryFirstPopup.vue
  src/components/amdin/Category/CategoryList.vue
  src/components/amdin/Category/CategorySecondPopup.vue
  src/components/amdin/Category/CategoryThirdPopup.vue
  src/components/amdin/Category/DeleteFirstPopup.vue
  src/components/amdin/Category/DeleteSecondPopup.vue
  src/components/amdin/Category/DeleteThirdPopup.vue
  src/components/amdin/Category/PostCategory.vue
  src/components/amdin/product/ProductDetailPopup.vue
  src/components/amdin/product/ProductList.vue
  src/router/router.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#51 refactoring ask FE(admin,franchise,favorite)
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/ask/AskFormView.vue
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/favorite/FavoriteRegister.vue
  src/components/log/Log.vue
  src/router/router.js
Labels: 🎨 Html&css, 🔨 Refactor

#57 refactoring ask FE(Admin,Franchise) font
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/ask/AskFormView.vue
  src/components/franchise/ask/Breadcrumb.vue
Labels: 🎨 Html&css, 🔨 Refactor

#59 refactoring favorite FE
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/favorite/FavoriteRegister.vue
Labels: 🎨 Html&css, 🔨 Refactor

#60 refactoring ask FE endpoint
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/ask/AskFormView.vue
Labels: 🔨 Refactor

#62 refactoring favorite FE endpoint
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/favorite/FavoriteRegister.vue
Labels: 🎨 Html&css, 🔨 Refactor

#63 View product with image and code, css refactoring
  src/components/amdin/Category/CategoryFirstPopup.vue
  src/components/amdin/Category/CategoryList.vue
  src/components/amdin/Category/CategorySecondPopup.vue
  src/components/amdin/Category/CategoryThirdPopup.vue
  src/components/amdin/Category/DeleteFirstPopup.vue
  src/components/amdin/Category/DeleteSecondPopup.vue
  src/components/amdin/Category/DeleteThirdPopup.vue
  src/components/amdin/Category/PostCategory.vue
  src/components/amdin/product/ProductDetailPopup.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
  src/components/franchise/product/FrProductDetail.vue
  src/components/franchise/product/FrProductList.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor, 📬 API

#64 refactoring ask FE
  package-lock.json
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/ask/AskFormView.vue
  src/components/login/AdminLogin.vue
Labels: 🎨 Html&css, 🔨 Refactor

#65 code refactoring update product by root
  src/components/amdin/product/ProductDetailPopup.vue
  src/components/amdin/product/ProductList.vue
Labels: 🎨 Html&css, 🔨 Refactor

#68 Refactoring and Add Config, Add icon, Driver Dashboard, View Notice for Root Admin
  src/App.vue
  src/assets/icon/Delivery.png
  src/assets/icon/admin.png
  src/assets/icon/smile.png
  src/assets/icon/speaker.png
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/config/footer/Footer.vue
  src/components/config/header/AdminHeader.vue
  src/components/config/header/DriverHeader.vue
  src/components/config/header/FranchiseHeader.vue
  src/components/config/header/RootAdmin.vue
  src/components/config/sidebar/sidebar.vue
  src/components/driver/driverDashBoard.vue
  src/components/login/AdminLogin.vue
  src/components/notice/noticeDetailsPopup.vue
  src/components/notice/noticeEditPopup.vue
  src/components/notice/noticeList.vue
  src/components/notice/noticeResisterPopup.vue
  src/router/router.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor, 📃 Docs

#69 refactoring ask FE
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/ask/AskFormView.vue
Labels: 🎨 Html&css, 🔨 Refactor

#70 3 types of login and token processing completed
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  server.js
  src/App.vue
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/FranchiseList.vue
  src/components/login/AdminLogin.vue
  src/components/login/DriverLogin.vue
  src/components/login/FranchiseLogin.vue
  src/main.js
  src/router/router.js
  src/store/store.js
Labels: ⚙ Setting, 🥰 Accessibility, 🎨 Html&css, 📬 API

#72 Refactoring layouts And Change file name
  src/App.vue
  src/components/layouts/footer/Footer.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/DriverHeader.vue
  src/components/layouts/header/FranchiseHeader.vue
  src/components/layouts/header/RootAdmin.vue
  src/components/layouts/sidebar/sidebar.vue
Labels: ⚙ Setting, 🎨 Html&css, 📃 Docs

#73 Code refactoring product and update product with props
  src/components/amdin/Category/CategoryFirstPopup.vue
  src/components/amdin/Category/CategoryList.vue
  src/components/amdin/Category/CategorySecondPopup.vue
  src/components/amdin/Category/CategoryThirdPopup.vue
  src/components/amdin/Category/DeleteFirstPopup.vue
  src/components/amdin/Category/DeleteSecondPopup.vue
  src/components/amdin/Category/DeleteThirdPopup.vue
  src/components/amdin/Category/PostCategory.vue
  src/components/amdin/product/ProductDetailPopup.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
  src/components/franchise/product/FrProductDetail.vue
  src/components/franchise/product/FrProductList.vue
  src/components/notice/noticeList.vue
  src/router/router.js
Labels: 🎨 Html&css, 🔨 Refactor

#78 Refactoring layouts, DriverDashBoard
  src/App.vue
  src/components/driver/DriverDashBoard.vue
  src/components/layouts/footer/Footer.vue
  src/components/layouts/header/RootAdminHeader.vue
  src/components/layouts/sidebar/SideBar.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#83 #29 refactoring ask FE
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/ask/AskFormView.vue
  src/components/franchise/ask/Breadcrumb.vue
Labels: 🎨 Html&css, 🔨 Refactor

#84 refactoring filter & bug fix with Lee
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
  src/components/franchise/product/FrProductList.vue
  src/router/router.js
Labels: 🐞 BugFix, 🔨 Refactor

#85 Refactoring routet.js And Notice Component
  src/components/notice/NoticeDetailsPopup.vue
  src/components/notice/NoticeEditPopup.vue
  src/components/notice/NoticeList.vue
  src/components/notice/NoticeResisterPopup.vue
  src/components/notice/noticeDetailsPopup.vue
  src/components/notice/noticeEditPopup.vue
  src/components/notice/noticeList.vue
  src/components/notice/noticeResisterPopup.vue
  src/router/router.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#86 Code refactoring url from categories
  src/components/amdin/Category/CategoryFirstPopup.vue
  src/components/amdin/Category/CategorySecondPopup.vue
  src/components/amdin/Category/CategoryThirdPopup.vue
  src/components/amdin/Category/DeleteFirstPopup.vue
  src/components/amdin/Category/DeleteSecondPopup.vue
  src/components/amdin/Category/DeleteThirdPopup.vue
  src/components/amdin/Category/PostCategory.vue
  src/components/amdin/product/ProductDetailPopup.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
Labels: 🔨 Refactor

#87 Refactoring Log FE
  src/components/log/Log.vue
Labels: 🎨 Html&css, 🔨 Refactor

#88 Refactoring add import to router.js/ NoticeList, DriverDashBoard
  src/components/driver/DriverDashBoard.vue
  src/components/notice/NoticeList.vue
  src/router/router.js
Labels: 🔨 Refactor
