Repository PI-Akatsuki/PIOMS.FE, pull requests merged in 2024-06, with the labels that each got.

#89 Refactor: refactoring favorite FE
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/favorite/FavoriteRegister.vue
  src/router/router.js
Labels: 🎨 Html&css, 🔨 Refactor

#93 Refactoring NoticeList for root and style (+socped), App.vue modify
  src/App.vue
  src/components/amdin/member/AdminMemberPage.vue
  src/components/notice/NoticeList.vue
  src/components/order/AdminOrderPage.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#94 Update popup with props end
  src/App.vue
  src/assets/css/Breadcrumb.css
  src/assets/css/order.css
  src/assets/css/popup.css
  src/components/amdin/product/ProductDetailPopup.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#95 After logging in, activate the header and logout button appropriate for your role.
  src/App.vue
  src/axios-instance.js
  src/components/layouts/footer/Footer.vue
  src/components/layouts/header/RootAdminHeader.vue
  src/components/login/AdminLogin.vue
  src/components/login/DriverLogin.vue
  src/components/login/FranchiseLogin.vue
  src/store/store.js
Labels: ⚙ Setting, 🎨 Html&css, ✨ Feature, 🔨 Refactor, 📬 API

#97 Product detail popup by FrOwner, up-to-date Excel
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductUpdatePopup.vue
  src/components/franchise/product/FrProductList.vue
  src/components/franchise/product/ProductDetailPopup.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#98 Refactor: refactoring Ask,Favorite, DashBoard FE
  src/assets/css/order.css
  src/assets/css/popup.css
  src/components/franchise/FranchiseDashBoard.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/franchise/favorite/FavoriteRegister.vue
Labels: 🎨 Html&css, 🔨 Refactor

#100 Mapping Product with FrWarehouse for count,enable
  src/components/amdin/member/AdminMemberPage.vue
  src/components/amdin/product/ProductList.vue
  src/components/franchise/product/FrProductList.vue
Labels: ✨ Feature, 🔨 Refactor

#104 View all admin members
  src/components/amdin/Category/DeleteFirstPopup.vue
  src/components/amdin/Category/DeleteSecondPopup.vue
  src/components/amdin/member/AdminMemberPage.vue
  src/components/amdin/member/AdminPostPopup.vue
  src/components/franchise/product/ProductDetailPopup.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#105 Refactor: refactoring Ask FE
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/ask/AskFormView.vue
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/favorite/FavoriteRegister.vue
  src/components/layouts/footer/Footer.vue
  src/router/router.js
Labels: ✨ Feature, 🔨 Refactor

#110 Fix Admin's pages(order,exchagne,notice,ask,product) css
  src/assets/css/order.css
  src/components/amdin/Category/CategoryList.vue
  src/components/amdin/Category/PostCategory.vue
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AskMain.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
  src/components/amdin/product/ProductUpdatePopup.vue
  src/components/exchange/AdminExchangePage.vue
  src/components/exchange/exchangeDetail.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/notice/NoticeDetailsPopup.vue
  src/components/notice/NoticeEditPopup.vue
  src/components/notice/NoticeList.vue
  src/components/notice/NoticeResisterPopup.vue
  src/components/order/AdminOrderDetail.vue
  src/components/order/AdminOrderPage.vue
Labels: 🐞 BugFix, 🎨 Html&css

#114 Refactoring Dashboard For Delivery Driver
  src/components/driver/DriverDashBoard.vue
  src/components/notice/NoticeList.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#115 Refactor: refactoring franchiseOwnerDashBoard, Ask FE
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/FranchiseDashBoard.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/log/Log.vue
Labels: 🎨 Html&css, 🔨 Refactor

#118 Refactoring Dashboard For Delivery Driver
  src/components/driver/DriverDashBoard.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#122 Refactor: refactoring franchiseOwnerDashBoard
  src/components/franchise/FranchiseDashBoard.vue
Labels: 🎨 Html&css, 🔨 Refactor

#127 View all drivers with excel by admin
  src/components/amdin/Category/DeleteFirstPopup.vue
  src/components/amdin/Category/DeleteSecondPopup.vue
  src/components/amdin/Category/DeleteThirdPopup.vue
  src/components/amdin/Category/PostCategory.vue
  src/components/amdin/member/DriverMemberPage.vue
  src/components/amdin/member/DriverPostPopup.vue
  src/components/amdin/product/ProductDeletePopup.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
  src/components/amdin/product/ProductUpdatePopup.vue
  src/components/franchise/product/FrProductList.vue
  src/components/log/Log.vue
  src/router/router.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#128 code refactoring and delete annotation
  src/components/amdin/Category/CategoryList.vue
  src/components/amdin/Category/PostCategory.vue
  src/components/amdin/product/ProductDeletePopup.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
  src/components/amdin/product/ProductUpdatePopup.vue
  src/components/franchise/product/FrProductList.vue
  src/components/franchise/product/ProductDetailPopup.vue
  src/components/order/FranchiseOrderPage.vue
Labels: 🔨 Refactor

#130 refactoring FrOwnerMemberPage FE
  src/components/franchise/member/FormEdit.vue
  src/components/franchise/member/FrOwnerMemberPage.vue
Labels: 🎨 Html&css, 🔨 Refactor

#131 Design, Feat: Add Root Admin Dashboard Sample
  src/components/amdin/dashboard/AdminDashBoard.vue
  src/router/router.js
Labels: 🎨 Html&css, ✨ Feature

#133 css update for product and categories
  src/components/amdin/Category/CategoryList.vue
  src/components/amdin/Category/PostCategory.vue
  src/components/amdin/product/ProductDeletePopup.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
  src/components/amdin/product/ProductUpdatePopup.vue
  src/components/franchise/product/ProductDetailPopup.vue
  src/components/order/FranchiseOrderPage.vue
Labels: 🎨 Html&css, 🔨 Refactor

#134 Refacotr: refactoring FranchiseOwnerDashBoard FE
  src/components/franchise/FranchiseDashBoard.vue
  src/router/router.js
Labels: 🎨 Html&css, 🔨 Refactor

#135 Edit Css overall
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/amdin/dashboard/AdminDashBoard.vue
  src/components/exchange/AdminExchangePage.vue
  src/components/exchange/exchangeDetail.vue
  src/components/exchange/exchangePopup.vue
  src/components/log/Log.vue
  src/components/order/AdminOrderPage.vue
Labels: 🥰 Accessibility, 🎨 Html&css

#138 refatoring Ask, FranchiseDashBoard, Log, FranchiseOrderPage
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/franchise/FranchiseDashBoard.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/ask/AskFormView.vue
  src/components/log/Log.vue
  src/components/order/FranchiseOrderPage.vue
Labels: 🎨 Html&css, 🔨 Refactor

#139 Refactoring DashBoard for Driver / Create Popup
  src/components/driver/DriverDashBoard.vue
  src/components/driver/DriverDashboardStatusPopup.vue
  src/components/driver/Invoice.vue
  src/components/notice/NoticeDetailsPopup.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#141 docs: add icon
  src/assets/icon/PIOMSDelivery.png
  src/assets/icon/invoicePrint.png
Labels: ⚙ Setting, 📃 Docs

#142 add admin dash board
  src/components/amdin/dashboard/AdminDashBoard.vue
  src/components/order/AdminOrderDetail.vue
  src/components/order/AdminOrderPage.vue
  src/components/order/FranchiseOrderDetail.vue
  src/components/order/FranchiseOrderPage.vue
  src/components/order/FranchiseOrderPopup.vue
  src/components/order/FranchiseOrderUpdatePopup.vue
  src/router/router.js
Labels: 🎨 Html&css

#145 fix: fix url
  src/components/exchange/AdminExchangePage.vue
Labels: 🐞 BugFix

#148 Add Print Fucntion
  src/components/driver/DriverDashBoard.vue
  src/components/driver/Invoice.vue
Labels: 🎨 Html&css, ✨ Feature

#150 Modify route guard and admin header
  index.html
  src/App.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/RootAdminHeader.vue
  src/router/router.js
Labels: 🎨 Html&css, ✨ Feature

#151 Refactor: refactoring Ask, FRDashBoard
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AnswerFormRegister.vue
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/FranchiseDashBoard.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/member/FrOwnerMemberPage.vue
  src/components/log/Log.vue
Labels: 🎨 Html&css, 🔨 Refactor

#152 Login token issue resolved
  src/App.vue
  src/axios-instance.js
  src/components/login/AdminLogin.vue
  src/router/router.js
  src/store/store.js
Labels: 🐞 BugFix

#153 : refactoring Ask, FRDashBoard, Favoirte, Header, Notice
  src/components/amdin/ask/AnswerFormEdit.vue
  src/components/amdin/ask/AskMain.vue
  src/components/franchise/FranchiseDashBoard.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/ask/AskFormCreate.vue
  src/components/franchise/ask/AskFormEdit.vue
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/favorite/FavoriteRegister.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/FranchiseHeader.vue
  src/components/notice/NoticeListFrOwner.vue
Labels: 🎨 Html&css, 🔨 Refactor

#155 NoticeDetailsPopup css
  src/components/notice/NoticeDetailsPopup.vue
  src/components/notice/NoticeList.vue
Labels: 🎨 Html&css, 🔨 Refactor

#154 Fix Order, admin dashboard css
  src/App.vue
  src/assets/css/order.css
  src/assets/css/popup.css
  src/components/amdin/dashboard/AdminDashBoard.vue
  src/components/amdin/invoice/AdminInvoice.vue
  src/components/amdin/member/AdminMemberPage.vue
  src/components/exchange/AdminExchangePage.vue
  src/components/exchange/FranchiseExchangeDetail.vue
  src/components/exchange/FranchiseExchangePage.vue
  src/components/exchange/exchangeDetail.vue
  src/components/exchange/exchangePopup.vue
  src/components/franchise/member/FormEdit.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/FranchiseHeader.vue
  src/components/order/AdminOrderDetail.vue
  src/components/order/AdminOrderPage.vue
  src/components/order/FranchiseOrderDetail.vue
  src/components/order/FranchiseOrderPage.vue
  src/components/order/FranchiseOrderPopup.vue
  src/components/order/FranchiseOrderUpdatePopup.vue
  src/router/router.js
Labels: 🐞 BugFix, 🥰 Accessibility, 🎨 Html&css, 📬 API

#156 Refactoring admin ProductList css
  src/components/amdin/product/ProductList.vue
Labels: 🎨 Html&css, 🔨 Refactor

#158 RefactoringDriverDashBoard css
  src/components/driver/DriverDashBoard.vue
Labels: 🎨 Html&css, 🔨 Refactor

#159 fix: fix button location
  src/components/amdin/product/ProductList.vue
Labels: 🎨 Html&css

#160 View product list for FrOwners
  src/components/amdin/Category/CategoryFirstPopup.vue
  src/components/amdin/Category/CategorySecondPopup.vue
  src/components/amdin/Category/CategoryThirdPopup.vue
  src/components/amdin/Category/DeleteFirstPopup.vue
  src/components/amdin/Category/DeleteSecondPopup.vue
  src/components/amdin/Category/DeleteThirdPopup.vue
  src/components/amdin/product/ProductList.vue
  src/components/amdin/product/ProductPostPopup.vue
  src/components/franchise/product/FrProductList.vue
  src/router/router.js
Labels: 🐞 BugFix, 🎨 Html&css, ✨ Feature, 🔨 Refactor

#161 fix: fix error when first login
  src/App.vue
  src/components/amdin/member/AdminMemberPage.vue
  src/components/amdin/member/DriverMemberPage.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/notice/NoticeResisterPopup.vue
  src/router/router.js
Labels: 🐞 BugFix

#163 Refactoring DriverDashBoard css, Invoice popup css
  src/components/driver/DriverDashBoard.vue
  src/components/notice/NoticeList.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#165 Refactor: refactoring Favorite FE
  src/components/franchise/favorite/FavoriteList.vue
  src/components/log/Log.vue
Labels: 🔨 Refactor

#169 Refactoring DriverDashBoard, Invoice popup, StatusPopup
  src/components/driver/DriverDashBoard.vue
  src/components/driver/DriverDashboardStatusPopup.vue
  src/components/driver/Invoice.vue
  src/components/layouts/header/DriverHeader.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#173 View all Franchise,Create,Update,Delete popup for Franchise
  src/components/admin/product/ProductList.vue
  src/components/franchise/FranchiseList.vue
  src/components/franchise/FranchisePostPopup.vue
  src/components/franchise/FranchiseUpdatePopup.vue
  src/components/franchise/product/FrProductList.vue
  src/components/layouts/header/AdminHeader.vue
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#174 Refactoring FranchiseOwner Header Css
  src/components/admin/dashboard/AdminDashBoard.vue
  src/components/franchise/FranchiseDashBoard.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/FranchiseHeader.vue
  src/components/notice/NoticeListFrOwner.vue
Labels: 🎨 Html&css, 🔨 Refactor

#175 bug fix by merge for Update Franchise
  src/components/franchise/FranchiseList.vue
  src/components/franchise/FranchisePostPopup.vue
  src/components/franchise/FranchiseUpdatePopup.vue
Labels: 🐞 BugFix, 🔨 Refactor

#176 fix css overall
  src/assets/css/order.css
  src/components/admin/member/AdminList.vue
  src/components/admin/member/DriverList.vue
  src/components/admin/product/ProductList.vue
  src/components/driver/DriverDashBoard.vue
  src/components/exchange/AdminExchangePage.vue
  src/components/exchange/FranchiseExchangePage.vue
  src/components/franchise/FranchiseList.vue
  src/components/franchise/member/FranchiseOwnerList.vue
  src/components/layouts/header/RootHeader.vue
  src/components/notice/NoticeList.vue
  src/components/order/AdminOrderPage.vue
  src/components/order/FranchiseOrderPage.vue
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#177 fix: fix franchiseHeader
  src/components/franchise/mypage/FranchiseInfo.vue
  src/components/layouts/header/FranchiseHeader.vue
  src/router/router.js
Labels: 🎨 Html&css

#178 Feature/layout
  src/components/admin/info/AdminUpdatePopup.vue
  src/components/admin/member/AdminList.vue
Labels: 🎨 Html&css, ✨ Feature, 📬 API

#180 FranchiseList excel download by admin
  src/components/franchise/FranchiseList.vue
Labels: ✨ Feature, 📬 API

#181 Refactoring FranchiseOwner Dashboard Css
  src/components/franchise/FranchiseDashBoard.vue
Labels: 🎨 Html&css, 🔨 Refactor

#182 Excel ,PDF stabilization
  src/assets/css/order.css
  src/components/admin/member/DriverList.vue
  src/components/exchange/FranchiseExchangePage.vue
  src/components/franchise/member/FranchiseOwnerList.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/RootHeader.vue
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API

#183 Refactoring FranchiseOwner FrWarehousePage Css
  src/components/franchise/warehouse/FrWarehousePage.vue
Labels: 🎨 Html&css, 🔨 Refactor

#184 Refactor: refacotoring Ask FE
  src/components/admin/ask/AskMain.vue
Labels: 🎨 Html&css, 🔨 Refactor

#185 Feature/layout
  src/assets/icon/가맹점등록.png
  src/assets/icon/공지사항등록.png
  src/assets/icon/배송기사등록.png
  src/assets/icon/이력관리.png
  src/assets/icon/점주등록.png
  src/components/admin/ask/AskMain.vue
  src/components/admin/category/CategoryFirstPopup.vue
  src/components/admin/category/CategoryList.vue
  src/components/admin/category/CategorySecondPopup.vue
  src/components/admin/category/CategoryThirdPopup.vue
  src/components/admin/category/DeleteFirstPopup.vue
  src/components/admin/category/DeleteSecondPopup.vue
  src/components/admin/category/DeleteThirdPopup.vue
  src/components/admin/category/PostCategory.vue
  src/components/admin/invoice/AdminInvoice.vue
  src/components/admin/member/AdminList.vue
  src/components/admin/member/AdminPostPopup.vue
  src/components/admin/member/DriverList.vue
  src/components/admin/product/ProductList.vue
  src/components/driver/info/DriverPostPopup.vue
  src/components/driver/info/DriverUpdatePopup.vue
  src/components/exchange/AdminExchangePage.vue
  src/components/franchise/FranchiseList.vue
  src/components/franchise/FranchiseUpdatePopup.vue
  src/components/franchise/member/FormEdit.vue
  src/components/franchise/member/FranchiseOwnerList.vue
  src/components/franchise/member/FranchiseOwnerPostPopup.vue
  src/components/franchise/member/FranchiseOwnerUpdatePopup.vue
  src/components/log/Log.vue
  src/components/notice/NoticeEditPopup.vue
  src/components/notice/NoticeList.vue
  src/components/order/AdminOrderPage.vue
  src/router/router.js
Labels: ⚙ Setting, 🎨 Html&css, ✨ Feature, 🔨 Refactor, 📬 API

#186 Refactoring FranchiseOwner Css
  src/assets/icon/즐겨찾기.png
  src/components/franchise/FranchiseDashBoard.vue
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/product/FrProductList.vue
  src/components/franchise/warehouse/FrWarehousePage.vue
Labels: 🎨 Html&css, 🔨 Refactor

#188 Modify Admin NoticeRegisterPopup CSS
  src/components/franchise/ask/AskFRMain.vue
  src/components/notice/NoticeResisterPopup.vue
Labels: 🐞 BugFix, 🎨 Html&css

#189 Refactoring Css for admin invoice, FrWarehouse, Product category
  src/components/admin/invoice/AdminInvoice.vue
  src/components/franchise/product/FrProductList.vue
  src/components/franchise/warehouse/FrWarehousePage.vue
Labels: 🎨 Html&css, 🔨 Refactor

#191 Fix error admin,root dashboard, header
  src/components/admin/dashboard/AdminDashBoard.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/RootHeader.vue
Labels: 🐞 BugFix

#192 Refactor: refactoring Ask Time
  src/components/admin/ask/AskMain.vue
Labels: 🔨 Refactor

#193 Feature/product
  src/components/driver/DriverDashBoard.vue
  src/components/driver/Invoice.vue
  src/components/notice/NoticeEditPopup.vue
  src/components/notice/NoticeList.vue
Labels: 🐞 BugFix, 🎨 Html&css, 🔨 Refactor

#194 Root & Admin Layout task completed
  src/App.vue
  src/components/admin/ask/AskMain.vue
  src/components/admin/category/CategoryList.vue
  src/components/admin/category/PostCategory.vue
  src/components/admin/invoice/AdminInvoice.vue
  src/components/admin/member/AdminList.vue
  src/components/admin/member/DriverList.vue
  src/components/admin/product/ProductList.vue
  src/components/exchange/AdminExchangePage.vue
  src/components/franchise/FranchiseList.vue
  src/components/franchise/member/FranchiseOwnerList.vue
  src/components/franchise/product/FrProductList.vue
  src/components/franchise/warehouse/FrWarehousePage.vue
  src/components/log/Log.vue
  src/components/notice/NoticeList.vue
  src/components/order/AdminOrderPage.vue
Labels: 🎨 Html&css

#195 Refactoring All NoticeList Page sort refactoring & Add Order Update Popup
  src/components/admin/dashboard/AdminDashBoard.vue
  src/components/franchise/FranchiseDashBoard.vue
  src/components/notice/NoticeList.vue
  src/components/notice/NoticeListFrOwner.vue
  src/components/order/FranchiseOrderUpdatePopup.vue
Labels: 🎨 Html&css, 🔨 Refactor

#196 'Develop' into 'main'
  src/App.vue
  src/components/admin/ask/AnswerFormRegister.vue
  src/components/admin/ask/AskMain.vue
  src/components/admin/category/CategoryList.vue
  src/components/admin/category/PostCategory.vue
  src/components/admin/dashboard/AdminDashBoard.vue
  src/components/admin/info/AdminPostPopup.vue
  src/components/admin/invoice/AdminInvoice.vue
  src/components/admin/member/AdminList.vue
  src/components/admin/member/DriverList.vue
  src/components/admin/product/ProductList.vue
  src/components/driver/DriverDashBoard.vue
  src/components/driver/Invoice.vue
  src/components/exchange/AdminExchangePage.vue
  src/components/franchise/FranchiseDashBoard.vue
  src/components/franchise/FranchiseList.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/member/FranchiseInfoPopup.vue
  src/components/franchise/member/FranchiseOwnerList.vue
  src/components/franchise/product/FrProductList.vue
  src/components/franchise/warehouse/FrWarehousePage.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/FranchiseHeader.vue
  src/components/layouts/header/RootHeader.vue
  src/components/log/Log.vue
  src/components/notice/NoticeEditPopup.vue
  src/components/notice/NoticeList.vue
  src/components/notice/NoticeListFrOwner.vue
  src/components/notice/NoticeResisterPopup.vue
  src/components/order/AdminOrderPage.vue
  src/components/order/FranchiseOrderUpdatePopup.vue
Labels: 🌏 Deploy

#197 Refactor: refactoring log FE
  src/components/log/Log.vue
Labels: 🎨 Html&css, 🔨 Refactor

#198 Edit Franchise Owner screen layout
  src/assets/icon/문의사항등록.png
  src/assets/icon/반품신청.png
  src/assets/icon/발주등록.png
  src/components/admin/info/AdminUpdatePopup.vue
  src/components/exchange/FranchiseExchangePage.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/product/FrProductList.vue
  src/components/franchise/warehouse/FrWarehousePage.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/FranchiseHeader.vue
  src/components/layouts/header/RootHeader.vue
  src/components/notice/NoticeList.vue
  src/components/notice/NoticeListFrOwner.vue
  src/components/order/FranchiseOrderPage.vue
Labels: 🐞 BugFix, 🎨 Html&css

#199 fix order product filter
  src/components/franchise/FranchiseDashBoard.vue
  src/components/order/FranchiseOrderPopup.vue
  src/components/order/FranchiseOrderUpdatePopup.vue
Labels: 🐞 BugFix, 🔨 Refactor

#200 Front filter minor size issue
  src/components/franchise/product/FrProductList.vue
Labels: 🎨 Html&css

#201 Fixed issue where store owner could not be registered
  src/assets/icon/문의사항등록.png
  src/assets/icon/반품신청.png
  src/assets/icon/발주등록.png
  src/components/admin/info/AdminUpdatePopup.vue
  src/components/driver/DriverDashBoard.vue
  src/components/driver/Invoice.vue
  src/components/driver/info/DriverInfoPopup.vue
  src/components/exchange/FranchiseExchangePage.vue
  src/components/franchise/FranchiseDashBoard.vue
  src/components/franchise/ask/AskFRMain.vue
  src/components/franchise/favorite/FavoriteList.vue
  src/components/franchise/member/FranchiseOwnerPostPopup.vue
  src/components/franchise/product/FrProductList.vue
  src/components/franchise/warehouse/FrWarehousePage.vue
  src/components/layouts/header/AdminHeader.vue
  src/components/layouts/header/DriverHeader.vue
  src/components/layouts/header/FranchiseHeader.vue
  src/components/layouts/header/RootHeader.vue
  src/components/log/Log.vue
  src/components/notice/NoticeList.vue
  src/components/notice/NoticeListFrOwner.vue
  src/components/order/FranchiseOrderPage.vue
  src/components/order/FranchiseOrderPopup.vue
  src/components/order/FranchiseOrderUpdatePopup.vue
Labels: 🐞 BugFix, ✨ Feature

#202 Modify code style
  src/components/admin/category/DeleteFirstPopup.vue
  src/components/admin/category/DeleteSecondPopup.vue
  src/components/admin/category/DeleteThirdPopup.vue
  src/components/admin/info/AdminUpdatePopup.vue
  src/components/driver/DriverDashBoard.vue
Labels: 🎨 Html&css
